@startuml

package domain.model.character.character {
  class Character {
    - int characterId
    - String name
    - ParameterList parameterList
    - BelongingList belongingList
  }

  class Human {
    - Job job
    - String school
    - String comeFrom
    - String mentalDisorder
    - String sex
    - int age
    - HumanType type
    - DetailList detailList
  }

  class Detail {
    int id
    DetailType type
    String detail
  }

  class DetailList {
    + ArrayList<Detail> detailList
    - void add(Detail detail)
  }

  enum DetailType {
    - int id
    + int getId()
    + DetailType getType(final int id)
  }

  Character <-- Human
}

package Factory {
  class HumanFactory {
    - ParameterListFactory parameterListFactory
    - BelongingListFactory belongingListFactory
    + Human create(int humanId, int characterId, String name, ParameterList parameterList, BelongingList belongingList, Job job, String school, String comeFrom, String mentalDisorder, String sex, int age, HumanType type, DetailList detailList)
    + Human createInit()
  }
}

@enduml
