@startuml

[*] --> top


state 探索者登録 {
  top --> character_top
  character_top -> character_detail : 詳細

  character_top -> character_top : 検索/ページング


  state 探索者追加 {
    character_top -> character_add : 新規追加
    character_add -> character_detail : 登録
  }

  state 探索者修正 {
    character_detail -> character_confirm : 修正
    character_confirm -> character_detail : 登録
  }

}


}
@enduml