@startuml

object CHARACTER_INFO {
  ID INT NOT NULL AUTO_INCREMENT
  NAME VARCHAR(20)
}

object HUMAN {
  ID INT NOT NULL AUTO_INCREMENT
  CHARACTER_ID INT NOT NULL
  JOB_ID INT, SCHOOL VARCHAR(20)
  COME_FROM VARCHAR(20)
  MENTAL_DISORDER VARCHAR(20)
  SEX VARCHAR(20)
  AGE INT
  HUMAN_TYPE INT
}

object MONSTER {
  ID INT NOT NULL AUTO_INCREMENT
  CHARACTER_ID INT NOT NULL
  ARMOR INT
  LACK_OF_SANITY VARCHAR(20)
  REMARKS VARCHAR(200)
}

object DETAIL{
  ID INT NOT NULL AUTO_INCREMENT
  CHARACTER_ID INT
  DETAIL_TYPE INT
  DETAIL VARCHAR(200)
}

object JOB {
  ID INT NOT NULL AUTO_INCREMENT
  NAME VARCHAR(20)
}

object JOB_DETAIL {
  ID INT NOT NULL AUTO_INCREMENT
  JOB_ID INT NOT NULL
  INVESTIGATE_TYPE INT
}

object BELONGING{
  ID INT NOT NULL AUTO_INCREMENT
  CHARACTER_ID INT
  BELONGING_TYPE INT
  NAME VARCHAR(20)
  DESCRIPTION VARCHAR(200)
}

object WEAPON {
  ID INT NOT NULL AUTO_INCREMENT
  NAME VARCHAR(20)
  ACCURACY INT
  DAMAGE INT
  RANGE INT
  REMARKS INT
}

object PARAMETER {
  ID INT NOT NULL AUTO_INCREMENT
  CHARACTER_ID INT
  PARAMETER INT
  DICE_VALUE VARCHAR(20)
  PARAMETER_TYPE INT
  DEFAULT_VALUE INT
  SUB_PARAMETER_TYPE INT
}

CHARACTER_INFO "1" -- "0..1" HUMAN
CHARACTER_INFO "1" -- "0..1" MONSTER
CHARACTER_INFO "1" -- "0..*" BELONGING
CHARACTER_INFO "1" -- "0..*" PARAMETER
HUMAN "1" .. "0..1" JOB
HUMAN "1" .. "0..*" DETAIL
JOB "1" .. "0..*" JOB_DETAIL
BELONGING "1" -- "0..1" WEAPON

@enduml